name: Node.js CI

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'node-lab-project'
          heroku_email: 'ramp8a799@gmail.com'
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Eslint
        run: |
          npm ci
      - name: Eslint working flow
        run: |
          npm run eslint
          npm run format
